cluster:
  name: agentic-rag-cluster

destinations:
  grafana-cloud-metrics:
    type: prometheus
    url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    auth:
      type: basic
      username: "3267520"
      password: "${GRAFANA_CLOUD_TOKEN}"
  grafana-cloud-logs:
    type: loki
    url: https://logs-prod-028.grafana.net/loki/api/v1/push
    auth:
      type: basic
      username: "1629435"
      password: "${GRAFANA_CLOUD_TOKEN}"

clusterMetrics:
  enabled: true
  collector: alloy-metrics

hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: false
  energyMetrics:
    enabled: true

costMetrics:
  enabled: true
  collector: alloy-metrics

clusterEvents:
  enabled: true
  collector: alloy-singleton

podLogsViaLoki:
  enabled: true
  collector: alloy-logs

collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
  alloy-singleton:
    presets:
      - singleton
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset

telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: false
  opencost:
    deploy: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: agentic-rag-cluster
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom
  kepler:
    deploy: true
